
comment: off

coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 10%
        base: auto
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
  range: 90..100
  round: down
  precision: 2

ignore:
  - "backend/src/main/java/com/statistics/core/config/*.java"
  - "backend/src/main/java/com/statistics/core/StatisticsApp.java"