export const TOURNAMENTS_SPORT_LOADING = 'TOURNAMENTS_SPORT_LOADING'
export const TOURNAMENTS_SPORT_FETCHED = 'TOURNAMENTS_SPORT_FETCHED'
export const TOURNAMENT_SPORT_CHOICE = 'TOURNAMENT_SPORT_CHOICE'