drop table if exists match_events CASCADE;
drop table if exists match_statistics CASCADE;
drop table if exists matches CASCADE;
drop table if exists rounds CASCADE;
drop table if exists sports CASCADE;
drop table if exists teams CASCADE;
drop table if exists tournaments CASCADE;
drop table if exists user_permissions CASCADE;
drop table if exists users CASCADE;
create table match_events
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    minute        integer,
    type          varchar(255),
    match_id      bigint,
    team_id       bigint,
    primary key (id)
);
create table match_statistics
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    name          varchar(255),
    title         varchar(255),
    type          varchar(255),
    value         integer,
    match_id      bigint,
    team_id       bigint,
    primary key (id)
);
create table matches
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    away_score    integer,
    date          timestamp,
    home_score    integer,
    state         varchar(255),
    away_team_id  bigint,
    home_team_id  bigint,
    round_id      bigint,
    primary key (id)
);
create table rounds
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    number        smallint,
    tournament_id bigint,
    primary key (id)
);
create table sports
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    title         varchar(255),
    primary key (id)
);
create table teams
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    title         varchar(255),
    tournament_id bigint,
    primary key (id)
);
create table tournaments
(
    id            bigint generated by default as identity,
    date_created  timestamp,
    date_modified timestamp,
    title         varchar(255),
    sport_id      bigint,
    primary key (id)
);
create table user_permissions
(
    user_id       bigint not null,
    permission_id integer
);
create table users
(
    id                            bigint generated by default as identity,
    date_created                  timestamp,
    date_modified                 timestamp,
    account_expire_date           timestamp,
    email                         varchar(255),
    first_name                    varchar(255),
    jwt_refresh_token             varchar(255),
    jwt_refresh_token_expire_date timestamp,
    last_name                     varchar(255),
    password                      varchar(255),
    role_id                       binary(255),
    primary key (id)
);
alter table match_events
    add constraint FKdid29vmxxv18fh9p07a9vjnkf foreign key (match_id) references matches;
alter table match_events
    add constraint FKm5qon0d2h6dwbl54f6hfsnnkw foreign key (team_id) references teams;
alter table match_statistics
    add constraint FKldtmogh5ymoeohy52kprf99xa foreign key (match_id) references matches;
alter table match_statistics
    add constraint FKna2g1r8e7ig65ab6unagba96b foreign key (team_id) references teams;
alter table matches
    add constraint FK2e8erbfecb0tjtq9iudg36bxu foreign key (away_team_id) references teams;
alter table matches
    add constraint FK8k68nekawp47js52dq8720voe foreign key (home_team_id) references teams;
alter table matches
    add constraint FKjqepgamspeqo5q36vffq2h593 foreign key (round_id) references rounds;
alter table matches
    add constraint FK7ijemrxoyi9o8mpwvmcgmsaii foreign key (id) references matches;
alter table rounds
    add constraint FKhub61cvyqvwkgyntpdlo016xe foreign key (tournament_id) references tournaments;
alter table teams
    add constraint FKo5qehaxeuk4i5bxwpf20dvcws foreign key (tournament_id) references tournaments;
alter table tournaments
    add constraint FKtfww9ee33aoy7mkoohd1t3d1o foreign key (sport_id) references sports;
alter table user_permissions
    add constraint FKkowxl8b2bngrxd1gafh13005u foreign key (user_id) references users;