## Port of backend server
server:
  port: 10000

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

jwt:
  secret: ${random.uuid}
  refresh-token-exp-ms: 1209600000
  access-token-exp-ms: 900000
